### ISSUE TITLE
composer require shopware/psh --dev fails

### ISSUE THREAD

**Issue by kurtwithslc** [shopwareLabs/psh#100]
die Installation schlägt fehl!
Umgebung: LINUX (Mittwald Server), PHP 7.2

Problem 1
    - Installation request for shopware/psh ^1.4 -> satisfiable by shopware/psh[v1.4.0].
    - Conclusion: remove symfony/dependency-injection v4.4.1
    - Conclusion: don't install symfony/dependency-injection v4.4.1
....
Installation request for symfony/dependency-injection (locked at v4.4.1, required as ~4.4) ...

Installation failed, reverting ./composer.json to its original content.

**Comment by fpesch** [comment]
Es scheint, als wenn eine Dependency in deiner `composer.json` einen Konflikt mit den PSH Projekt dependencies hat.
Hier empfiehlt sich, die `.phar` Datei einzubinden.

**Comment by JanPietrzyk** [comment]
Denk ich auch, das passiert bei composer dev requirements leider immer wieder. siehe #105 #98
