### ISSUE TITLE
php-cs-fixer max Version PHP 7.1.*

### ISSUE THREAD

**Issue by kurtwithslc** [shopwareLabs/psh#101]
Bei der Installation per git clone https://github.com/shopwareLabs/psh.git 
schlägt der Befehl ./psh unit  fehl, da u.a. eine PHP Version von max 7.1 gefordert wird
...
(1/1) Output from
> bin/php-cs-fixer fix
	PHP needs to be a minimum version of PHP 5.3.6 and maximum version of PHP 7.1.*
	Executed with failure

**Comment by JanPietrzyk** [comment]
This is resolved by bumping the required version to 7.2 in a future release.(#106)

If you happen to develop wuith an older version there is a `run.sh` that will execute the tests inside a PHP 7.0 Docker-Container
