### ISSUE TITLE
Phar archive via composer

### ISSUE THREAD

**Issue by fpesch** [shopwareLabs/psh#105]
I suggest that a separate composer package containing the phar archive only is being set up.
Loading the phar file via composer is much more convenient. 
Especially because minor versions and bugfixes are automatically updated if using the correct version constraints in your `composer.json`.

[PHPStan](https://github.com/phpstan/phpstan), [Psalm](https://github.com/psalm/phar) and [Deptrac](https://github.com/sensiolabs-de/deptrac-shim) are just some examples of projects using this approach.

**Comment by JanPietrzyk** [comment]
Really good idea! 

BTW might be time to get the whole version management stuff started. Up until now this is just a tag on the source, but nothing in the created file, which means packagist is the only one able to distinguish versions. The downloaded phar is always the most recent.

**Comment by fpesch** [comment]
[This](https://semver.org/) might be interesting for you then.

**Comment by JanPietrzyk** [comment]
Ok, after investigating a little further it looks like the whole deployment process is currently not working... I'll find a solution asap

**Comment by fpesch** [comment]
Closing this since it has been added.
