### ISSUE TITLE
Xml ist invalide

### ISSUE THREAD

**Issue by dbeier** [shopwareLabs/psh#110]
Meine .psh.xml enthält folgenden Inhalt und ich erhalte die Fehlermeldung "The schemaOrCallable argument has to be a valid path to XSD file or callable.". Ich benutze die von euch bereitgestellte phar.

```
<?xml version="1.0" encoding="UTF-8"?>

<psh xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/shopwareLabs/psh/master/resource/config.xsd">

    <header>TEST</header>
    <import path="tests"/>
    <import path="**/*"/>
    <path>actions</path>
</psh>
```

**Comment by JanPietrzyk** [comment]
Hi Daniel, freut mich sehr! 

Das Deployment ist leider vor einiger Zeit kaputt gegangen und wir habens nicht gemerkt. Ich arbeite bereits dran.

Zwischenzeitlich solltest du eine funktionierende Phar hier runterladen können: https://github.com/shopwareLabs/psh-phar

**Comment by JanPietrzyk** [comment]
Same problem as #105
