### ISSUE TITLE
Bug: Only one included script is executed

### ISSUE THREAD

**Issue by momocode-de** [shopwareLabs/psh#112]
I have a similar directory structure to the shopware 6 development template:

```
dev-ops
-- common
---- actions
---- scripts
------ my-script.sh
-- testenv
---- actions
------ my-action.sh
---- scripts
------ my-second-script.sh
```

The "scripts" directories should contain bash scripts that are used in actions. But they should not get called as an action, thats why there is a special directory for them.

This is the "my-action.sh":

```
#!/usr/bin/env bash
#DESCRIPTION: My action

INCLUDE: dev-ops/common/scripts/my-script.sh
INCLUDE: dev-ops/testenv/scripts/my-second-script.sh
```

For whatever reason only the second script is executed now. There is only 1/1 step. If I remove the second script, the first script is working. But if I add the second script again, the first script is skipped again.

I'm using the current psh.phar downloaded today. Am I doing something wrong, or is that a bug?

**EDIT:** The problem only occurs if I include scripts having the `# <PSH_EXECUTE_THROUGH_CMD>` comment. If I remove that from my scripts and just add a `echo Hello` every script is executed.

**Comment by JanPietrzyk** [comment]
Interesting. AFAIK this is a combination that is not tested by the test suite, aka uncharted territory :) . You are right, that should work. I'll take a look. Thank you for your report!

**Comment by JanPietrzyk** [comment]
fixed
