### ISSUE TITLE
sub environments

### ISSUE THREAD

**Issue by teiling88** [shopwareLabs/psh#18]
it would be great if we can create nested environments. As an example:

default init for local dev environment: 
./psh.pahr init 

default init for local dev environment with docker 7.1 container: 
./psh.phar init:php7.1

default init for ci environment: 
./psh.pahr ci:init 

default init for local dev environment with docker 7.1 container: 
./psh.phar ci:init:php7.1

**Comment by janwalther** [comment]
Alternatively psh could offer to use additional arguments to be used in shell scripts.
./psh.phar init php71
And in init.sh $1 would be "php71". This would also offer more flexibility if more arguments are needed. What do you think?

**Comment by JanPietrzyk** [comment]
@janwalther Thanks for the Feedback! To me this looks like a seperate issue. I personally prefer having as much as possible predetermined in the `.psh.yml` config file.

But I see the benefit in having command line parameters, as in any other application. I will open a new Issue for this.
