### ISSUE TITLE
Constant concatenating

### ISSUE THREAD

**Issue by janbuecker** [shopwareLabs/psh#20]
I have a command which uses 2 constants, `__APP_HOST__` and `__APP_PATH__`. The command needs both constants concatenated to create a url.

**Example values**

```
APP_HOST: 'github.com'
APP_PATH: '/shopwareLabs/psh'
```

**Example command**

```
curl http://__APP_HOST____APP_PATH__
```

**Expected result**

```
curl http://github.com/shopwareLabs/psh
```

**Given result**

```
PHP Fatal error:  Uncaught RuntimeException: Missing required value for "APP_HOST____APP_PATH" in phar:///Users/jb/web/master/psh.phar/src/ScriptRuntime/TemplateEngine.php:55
```

**Comment by bcremer** [comment]
Try it with a null byte: `curl http://__APP_HOST__\0__APP_PATH__`

**Comment by bcremer** [comment]
`curl http://$(a="__APP_HOST__"; b="__APP_PATH__"; echo $a$b)`

**Comment by JanPietrzyk** [comment]
The regex seems a little too gready, @teiling88 want's to take a look. Thanks for the nice description @janbuecker this can easily be distilled into a test :)
