### ISSUE TITLE
Add scrutinizer badges

### ISSUE THREAD

**Issue by JanPietrzyk** [shopwareLabs/psh#23]
Update README.md with badges and add code coverage to travis

**Comment by bcremer** [comment]
![badger!](https://upload.wikimedia.org/wikipedia/en/0/04/Badgers_Badgers.gif)

**Comment by theofidry** [comment]
A packagist badge would be nice as well

**Comment by teiling88** [comment]
@JanPietrzyk what do you think about https://codecov.io/ for display the code coverage? 
As a nice improvement in every pr we could see the improvement of the code coverage :)

**Comment by teiling88** [comment]
Fixed with: https://github.com/shopwareLabs/psh/pull/62/commits/ae34774c65687cbdcc2b513b30b28620f365c194
