### ISSUE TITLE
Command description

### ISSUE THREAD

**Issue by SimonBaeumer** [shopwareLabs/psh#34]
It would be nice if a description could be provided to a command. What do you think @JanPietrzyk?

**Comment by JanPietrzyk** [comment]
Good idea! The description would have to be a part of the `.sh` file, like a header maybe?

```
#!/usr/bin/env bash
# DESCRIPTION: The command description
```
Like that @SimonBaeumer ?

**Comment by bcremer** [comment]
Almost good, but please use `DESCRIPTION` instead of `DECSRIPTION` ;)

**Comment by SimonBaeumer** [comment]
@JanPietrzyk Yes, that looks good to me!
@bcremer :+1: Directly edited the title ^^

**Comment by JanPietrzyk** [comment]
WIP by #38

**Comment by JanPietrzyk** [comment]
resolved with #39
