### ISSUE TITLE
override .psh.yml

### ISSUE THREAD

**Issue by SimonBaeumer** [shopwareLabs/psh#35]
It would be nice to provide more than one configuration file, i.e. through a `.psh.yml.override`.

**Comment by JanPietrzyk** [comment]
Hmm, here I would need a little bit more context how this should be used... Can give me a use case exemplifying the feature?

**Comment by PascalThesing** [comment]
Perhaps he means inheritance or just splitting the file in multiple files.

**Comment by SimonBaeumer** [comment]
Would be nice to define a `psh.yml.override` which will be loaded after the `.psh.yml` to provide custom configurations if you use a base `.psh.yml` file. I.e. https://github.com/shopwareLabs/plugin-dev-tools provide a `.psh.yml` and to customize it for a specific project we could use overrides.

Further the configuration files should be merged, at the moment the `.psh.yml` will replace the complete `.psh.yml.dist`

**Comment by teiling88** [comment]
I think we can close this issue because of this pr: https://github.com/shopwareLabs/psh/pull/42

Any opinion @SimonBaeumer, @JanPietrzyk?

**Comment by SimonBaeumer** [comment]
Can be closed :+1:
