### ISSUE TITLE
creating selfupdate command

### ISSUE THREAD

**Issue by teiling88** [shopwareLabs/psh#53]
Since psh is used more and more - a psh command like composer selfupdate would be very nice.

**Comment by theofidry** [comment]
https://github.com/humbug/phar-updater is what you're looking for :)

**Comment by JanPietrzyk** [comment]
@theofidry nice library! Why is it part of the humbug organization?

**Comment by teiling88** [comment]
@theofidry - I already created a branch with this library :-) seems to be a good choice for this task.

**Comment by theofidry** [comment]
Why not? :) It was originally owned by padraic, but moved to Humbug to ease it's management. Humbug have some serious requirements for PHARs which is why it has a couple of PHARs related libraries under its umbrella even if it doesn't use them to their fullest yet
