### ISSUE TITLE
Implement a plugin system

### ISSUE THREAD

**Issue by svenfinke** [shopwareLabs/psh#68]
There might be functions that are useful for PSH, but not in every project. I think about stuff that adds some convenience, like bridges for other tools like ant or the symfony cli. As these tools are not used in every project, it would be great to have a plugin system that provides the possibility to add these commands.

**Why am I not simply adding scripts?**

I'm thinking about adding functionality that goes beyond a simple command. Thins like loading commands from ant or symfony. The plugins could be adding dynamic collections of commands. Of course, this could be done by adding a bridge script that gets the command as a parameter, but then you lose features like a complete list of commands, the search and autocompletion.

**How?**

I'm not sure about that... probably we could provide an interface with functions that need to be implemented, and psh is going the collection of plugins and calling the necessary functions from the plugins. The most simple plugin would only contain one .php file, more complex stuff could make use of separate services that are used by this class. But I'm not too happy with this... any other ideas?

**Comment by JanPietrzyk** [comment]
still relevant @svenfinke ?
