### ISSUE TITLE
Parse symfony cli commands

### ISSUE THREAD

**Issue by svenfinke** [shopwareLabs/psh#69]
_**I'd like to implement this as one of the first plugins for the plugin system.**_

Since this is used in projects with other "command collections" - like the symfony cli - it might be convenient to offer the possibility to parse these and use psh as the single interaction point. In combination with psh-global, this would provide things like autocomplete for the symfony cli.

Symfony is not providing a simple list with just the commands and no overhead, so the parsing might be quite tedious. To enable a fast autocompletion and a good overall performance, it might be a good idea to introduce a command cache.

The commands should probably be prefixed with a custom name and the group header should describe that these commands are not coming from psh.

**Comment by JanPietrzyk** [comment]
still relevant @svenfinke?
