### ISSUE TITLE
Multiple paths per environment

### ISSUE THREAD

**Issue by janbuecker** [shopwareLabs/psh#70]
Given a software project with a set of environments, you may want to use the existing environment with some 3rd party scripts.

**Example use case**
A simple example would be a software project with some environments like local or CI and an extension for that project which comes from another repository. You now want to use the environment from the main project and run your own scripts provided from the extension repository in the same CI environment without duplicating the whole environment itself into that extension.

My current solution is to copy the scripts into the core environments but that's a little bit hacky...

A change to psh could be to extend an existing environment by specifying multiple paths to read from. Maybe it is possible to solve this problem with #18 ?

**Comment by JanPietrzyk** [comment]
@janbuecker I'm a little confused, doesn't this already work?

see: 

https://github.com/shopwareLabs/psh/blob/be53baa4077aadd1e995bb5f2fa28a8d5cc4d293/tests/Acceptance/_app/.psh.yml#L25

**Comment by JanPietrzyk** [comment]
already implemented
