### ISSUE TITLE
Increase process time limit

### ISSUE THREAD

**Issue by pascalheidmann-bedarf** [shopwareLabs/psh#77]
When I try to run psh unit tests for [SwagImportExport](https://github.com/shopwareLabs/SwagImportExport/) I run into timeout issues as Symfony Process kills processes by default after 60 seconds running.
Either increasing this limit globally or as a CLI option would be a very welcome addition.

**Comment by teiling88** [comment]
Our tests in the b2b suite runs with code coverage at least 30 minutes. Are you sure this is an issue from psh?

**Comment by pascalheidmann-bedarf** [comment]
I don't know how those tests are designed but just running `./psh docker:init` for SwagImportExport already crashes after 60 seconds on my macbook. As setting up a docker instance for the first time can be time consuming if the resources aren't cached yet that might be the problem.
Anyway adding a `--timeout [seconds]` option would help in these situations and shouldn't be that hard to implement.

**Comment by teiling88** [comment]
> SwagImportExport already crashes after 60 seconds on my macbook.

What kind of error message do you receive? I guess your max_execution_time for php-cli is set to 60 seconds because psh works as an example in [shopware-docker](https://github.com/shopwareLabs/shopware-docker) flawless.

> Duration: 9m 32s
> All commands successfully executed!

**Comment by pascalheidmann-bedarf** [comment]
@teiling88 AFAIK you can't set `max_execution` time for cli?
Anyway: `$ php -i | grep max_execution` gives me `max_execution_time => 0 => 0` aka no limit

Trying to run shopware-docker I do not get any (relevant) error and it builds as expected.
But it also prints a lot of stuff while in SwagImportExport there is no output, just changes in the terminal title (tr, dirname, bash) which might result in Symfony thinking the process is stale and killing it...

**Comment by teiling88** [comment]
But then change it in the SwagImportExport repo or? This behaviour should be easy to fix.

**Comment by pascalheidmann-bedarf** [comment]
@teiling88 yeah the main fix should be in SwagImportExport but I still would love that option to set timeouts independently right in psh ;)

**Comment by teiling88** [comment]
psh is open source, so feel free to create a pull request ;-)

**Comment by JanPietrzyk** [comment]
@pascalheidman-bedarf  PSH executes commands in a subprocess (symfony/process). And we already set the execution limit to `0` (no limit) for every command 
see https://github.com/shopwareLabs/psh/blob/52e41a15111d5cb56bf1358598c8653e5d7a0c88/src/ScriptRuntime/ProcessExecutor.php#L129

So max execution time for the subprocess schould not be an issue, I belive. Also a timeout would trigger an Exception 
see
https://github.com/symfony/process/blob/1a01d2984ed07841fe3db2da69743f9b2ee14de7/Process.php#L1227

The question is If somehow PSH itself crashes. Is there really no output? Maybe it is a broken pipe? 

You could try to execute the command directly. PSH outputs every command it attempts to execute before execution. Something like this:

```
(1/3) Starting
> mysql -u app -papp -h mysql --port=3306 -e "DROP DATABASE IF EXISTS \`shopware\`"
```
You could just execute it yourself and see what the result is.

**Comment by JanPietrzyk** [comment]
Closing this as there are no new updates....
