### ISSUE TITLE
Shortcut for including other actions

### ISSUE THREAD

**Issue by nlubisch** [shopwareLabs/psh#83]
Im writing some scripts and want to include other tasks i've written before.
I kinda find it tedious to write absolute / relative paths for some task.
It's also hard to read especially relative paths like this one: https://github.com/shopware/shopware/blob/5.5/dev-ops/bamboo.shopware.com/actions/init.sh

I wish i could write something like the following in my scripts to include other actions.

```bash
#!/usr/bin/env bash

ACTION: shopware:update # Reference to dev-ops/shopware/actions/update.sh
ACTION: unit # Reference to dev-ops/common/actions/unit.sh
```

**Comment by JanPietrzyk** [comment]
nice! go for it if you like

**Comment by JanPietrzyk** [comment]
done
