### ISSUE TITLE
The schemaOrCallable argument has to be a valid path to XSD file or callable. 

### ISSUE THREAD

**Issue by Forestsoft-de** [shopwareLabs/psh#94]
Using the psh.phar file cause an error with an xml configuration file.
config.xsd doesnt exist.

jenkins@forestsoft:/www/shopware-plugins/plugin-builder$ bin/psh.phar -v
PHP InvalidArgumentException:  The schemaOrCallable argument has to be a valid path to XSD file or callable. in phar:///www/shopware-plugins/plugin-builder/bin/psh.phar/vendor/symfony/config/Util/XmlUtils.php on line 88
PHP Stack trace:
PHP   1. {main}() /www/shopware-plugins/plugin-builder/bin/psh.phar:0
PHP   2. require() /www/shopware-plugins/plugin-builder/bin/psh.phar:10
PHP   3. Shopware\Psh\Application\Application->run($inputArgs = array (0 => 'bin/psh.phar', 1 => '-v')) phar:///www/shopware-plugins/plugin-builder/bin/psh.phar/psh:12
PHP   4. Shopware\Psh\Application\ApplicationFactory->createConfig($rootDirectory = '/www/shopware-plugins/plugin-builder', $params = array (0 => 'bin/psh.phar', 1 => '-v')) phar:///www/shopware-plugins/plugin-builder/bin/psh.phar/src/Application/Application.php:67
PHP   5. Shopware\Psh\Config\XmlConfigFileLoader->load($file = '/www/shopware-plugins/plugin-builder/.psh.xml', $params = array ()) phar:///www/shopware-plugins/plugin-builder/bin/psh.phar/src/Application/ApplicationFactory.php:54
PHP   6. Shopware\Psh\Config\XmlConfigFileLoader->loadXmlRoot($file = '/www/shopware-plugins/plugin-builder/.psh.xml') phar:///www/shopware-plugins/plugin-builder/bin/psh.phar/src/Config/XmlConfigFileLoader.php:67
PHP   7. Symfony\Component\Config\Util\XmlUtils::loadFile($file = '/www/shopware-plugins/plugin-builder/.psh.xml', $schemaOrCallable = 'phar:///www/shopware-plugins/plugin-builder/bin/psh.phar/src/Config/../../resource/config.xsd') phar:///www/shopware-plugins/plugin-builder/bin/psh.phar/src/Config/XmlConfigFileLoader.php:195

The schemaOrCallable argument has to be a valid path to XSD file or callable.

**Comment by JanPietrzyk** [comment]
Sorry was on vacation :). Hmm, from the Symfony source my guess would be that the config file itself is not valid, aka does not comply with the schema (https://github.com/shopwareLabs/psh/blob/master/resource/config.xsd). Maybe you could post your psh.xml file so I could take a look?

Other than that the message itself of course is bonkers... The Exception should be caught and replaced with a real message.

**Comment by DaSpors** [comment]
Any news on this? 
Having the same issue over here except that the Exception is now caught and just the message printed.

As the docs reference psh I think this should have a much higher priority.
[https://docs.shopware.com/en/shopware-platform-dev-en/how-to/add-admin-new-column?category=shopware-platform-dev-en/how-to](https://docs.shopware.com/en/shopware-platform-dev-en/how-to/add-admin-new-column?category=shopware-platform-dev-en/how-to)

**Comment by manticorp** [comment]
I see a pull request has been made - any chance of this being fixed?

**Comment by cainydev** [comment]
Hi, I am getting that same error today. I installed psh using composer and created a .psh.xml in my root folder. Upon calling .psh.phar I get the red error message `The schemaOrCallable argument has to be a valid path to XSD file or callable.`

How can I work around this? As my xml file, it is just the minimal configuration from the readme file.
