### ISSUE TITLE
Update installation instructions to reflect not suitable for composer dependency

### ISSUE THREAD

**Issue by manticorp** [shopwareLabs/psh#98]
The installation instructions suggest it can be used as a composer dependency:

> Installation
> **Although you can use PSH as a composer dependency**, we recommend to use the PHAR archive instead. PSH only communicates through the shell with your application and therefore does not need any influence on your other project dependencies.

However, apparently this is not the case:

> psh should be used as an phar archive and not as a composer requirement.
> 
> _Originally posted by @teiling88 in https://github.com/shopwareLabs/psh/issues/97#issuecomment-616419631_

**Comment by JanPietrzyk** [comment]
Yes you *can* use it as a dependency through composer. But that means that all dependencies of psh will be mixed into your requirements and that you will have to manage them as well. This is what composer is trying to tell you there and this is why we have a phar for this. 

Alternatively you could use https://github.com/bamarni/composer-bin-plugin. This is why the composer installation can't simply be removed.
